Awesome-books
AtillaTahak/Awesome-books pull request #1
Opened 2021-10-25 11:07 UTC by AtillaTahak

-added necessary file and create skeleton on HTML

2021-10-25 17:55 UTC, Lameck1 requested changes
Hi, @AtillaTahak, 

Good job so far!
We have some issues to work on for us to move ahead though.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-25 17:55 UTC, Lameck1 commented on js/main.js
> +}
- Currently, the app doesn't function as expected. I am not able to create, add or remove a book. I am going to leave suggestions that you can work with below.

1. At line 9 above we get the following error 👇🏼 
![error](https://user-images.githubusercontent.com/45002654/138742597-aac44489-8379-49ba-babe-c4fa7e7424de.png)

In the error above we get a reference to line 27 where the `createBook` Method is being called. Why is this happening? When starting the app, nothing is really persisted in the `localStorage` and thus a reference to `null`(Look at line 25 where you are trying to reassign `bookList` to a property in the `localStorage`).

### Suggettion
Follow suggestions in the thread below 👇🏼

2021-10-25 17:55 UTC, Lameck1 commented on js/main.js
> +    const element = document.createElement('books');
- [ ] There is no element called `books`, even though HTML will create it for you, it is not semantically right.
```suggestion
    const element = document.createElement('li');
```

2021-10-25 17:55 UTC, Lameck1 commented on js/main.js
> +    </li>`;
- [ ] Since we are creating `li` tag up there, now remove the `li` tags in this template string.
```suggestion
    element.innerHTML += `
        <p>${e.bookNames}</p>
        <p>${e.authorNames}</p>
        <input type="button" value="remove" onclick="removeBook(this.id)" id="${bookElement.length}">
        <hr>`;
```

2021-10-25 17:55 UTC, Lameck1 commented on js/main.js
> +let bookList = [];
- [ ] For us not to keep reassigning this variable and making reference to a null value, refactor as below.
```suggestion
let bookList = JSON.parse(localStorage.getItem('books')) || [];
```

2021-10-25 17:55 UTC, Lameck1 commented on js/main.js
> +});
- [ ] Now remove this reassignment of the bookList variable
```suggestion
window.addEventListener('load', () => {
  createBook(bookList);
});
```

2021-10-26 07:02 UTC, rloterh commented on index.html
> +
- [ ] OPTIONAL
Kindly ensure not to leave empty lines in your code which do not serve any purpose, so as to keep your code well organized.

2021-10-26 07:02 UTC, rloterh commented on js/main.js
> +function createBook(bookElement) {
- [ ] OPTIONAL
It is a nice idea to prefer _arrow functions_ over normal functions, so as to keep your _function_ syntax simpler and cleaner.

2021-10-26 07:02 UTC, rloterh commented on js/main.js
> +    const element = document.createElement('books');
This issue is well resolved! ✔️

2021-10-26 07:02 UTC, rloterh commented on js/main.js
> +    </li>`;
This issue is well resolved! ✔️

2021-10-26 07:03 UTC, rloterh commented on js/main.js
> +let bookList = [];
This issue is well resolved! ✔️

2021-10-26 07:03 UTC, rloterh commented on js/main.js
> +});
This issue is well resolved! ✔️

2021-10-26 07:05 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi Mesi & Atilla, 

Your project is complete! Great job for making the necessary changes recommended by the previous reviewer(s). There is nothing else to say other than... it's time to merge it 🍾 :shipit:.
Congratulations! 🎉🥂

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

_Kindly consider my comment(s) marked **[OPTIONAL]** under this review:_
<br>
Cheers and Happy coding!👏 💻 🍷 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 1 more limited review per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-26 07:14 UTC, merged